### ISSUE TITLE
Timzone problem

### ISSUE THREAD

**Issue by chautran123** [GridProtectionAlliance/projectalpha#1]
I have problem when change time zone of connect device in Projectalpha. When i set timezone of new Device in openPDC is "Select TimeZone", the timestamp in Monitoring Divice Output is 04:00:00 (example). But, when i set timezone to UTC+7- Bangkok, Hanoi, Jakarta( My local zone) the timestamp in Monitoring Divice Output is 21:00:00, not look like my local time in my computer. I don't know why. Please help!
Thank!

**Comment by ritchiecarroll** [comment]
The timestamp in monitored devices is always reported in UTC.

Thanks,
Ritchie
